#include<stdio.h>
#include<dos.h>
#define WHITE "\x1b[37m"
#define RED "\x1b[31m"
#define BLUE "\x1b[34m"
#define CYAN "\x1b[36m"
#define MAGENTA "\x1b[35m"
#define UNDERLINE "\x1b[4m"
#define WHITEHIGHLIGHT "\x1b[7m"
#define BLACK "\x1b[8m"
#define CUT "\x1b[9m"
#define BOLD "\x1b[1m"
#define GREY "\x1b[2m"
#define LIGHTGREY "\x1b[3m"
#define DOUBLEUNDERINE "\x1b[21m"
#define GREEN "\x1b[32m"
#define YELLOW "\x1b[33m"
#define BLACKBACKGROUND "\x1b[40m"
#define REDBACKGROUND "\x1b[41m"
#define GREENBACKGROUND "\x1b[42m"
#define YELLOWBACKGROUND "\x1b[43m"
#define BLUEBACKGROUND "\x1b[44m"
#define MAGENTABACKGROUND "\x1b[45m"
#define CYANBACKGROUND "\x1b[46m"
#define WHITEBACKGROUND "\x1b[47m"
#define ABOVELINE "\x1b[53m"
#define SIMPLE "\x1b[0m"


